name: Build Container
run-name: Container build
on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  REGISTRY: quay.io
  IMAGE_REPOSITORY: cyclops-k8s
  IMAGE_NAME: ansible-kubernetes-devcontainer
jobs:
  build-and-push-image:
    runs-on: cyclops-k8s-runners
    permissions:
      contents: read
      # attestations: write
      # id-token: write
    steps:
      - name: Get environment variables
        run: env

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          password: ${{ secrets.QUAY_TOKEN }}
          username: ${{ secrets.QUAY_USER }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --yes libatomic1 skopeo

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Skopeo login to registry
        run: echo "${{ secrets.QUAY_TOKEN }}" | skopeo login ${{ env.REGISTRY }} --username "${{ secrets.QUAY_USER }}" --password-stdin

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          # cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          imageTag: latest #,ubuntu-lts,ubuntu-lts-24.04
          platform: linux/amd64 #,linux/arm64
          push: always
          runCmd: echo

      - name: Skopeo login to registry
        run: echo "${{ secrets.QUAY_TOKEN }}" | skopeo login ${{ env.REGISTRY }} --username "${{ secrets.QUAY_USER }}" --password-stdin

      - name: List container images
        run: docker image ls -a

      - name: List /tmp files
        run: ls -alh /tmp

      - name: Generate Trivy json report
        uses: aquasecurity/trivy-action@0.33.1
        # env:
        #   TRIVY_SKIP_DB_UPDATE: true
        #   TRIVY_SKIP_JAVA_DB_UPDATE: true
        with:
          exit-code: 0
          format: json
          hide-progress: true
          # image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          input: /tmp/output.tar.gz
          list-all-pkgs: true
          output: trivy-report.json
          scanners: vuln,secret,config,license
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          vuln-type: os,library

      - name: Upload Trivy json report
        uses: actions/upload-artifact@v5
        with:
          name: trivy-report-json
          path: trivy-report.json
          retention-days: 30

      - name: Generate Trivy html report
        uses: aquasecurity/trivy-action@0.33.1
        with:
          exit-code: 0
          format: template
          hide-progress: true
          # image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          input: /tmp/output.tar.gz
          list-all-pkgs: true
          output: trivy-report.html
          scanners: vuln,config
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          skip-setup-trivy: true
          template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
          vuln-type: os,library

      - name: Upload Trivy html report
        uses: actions/upload-artifact@v5
        with:
          name: trivy-report-html
          path: trivy-report.html
          retention-days: 30

      - name: Generate Trivy XML report
        uses: aquasecurity/trivy-action@0.33.1
        with:
          exit-code: 0
          format: template
          hide-progress: true
          # image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          input: /tmp/output.tar.gz
          list-all-pkgs: true
          output: trivy-report.xml
          scanners: vuln,secret,config,license
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          skip-setup-trivy: true
          template: "@$HOME/.local/bin/trivy-bin/contrib/junit.tpl"
          vuln-type: os,library

      - name: Upload Trivy XML report
        uses: actions/upload-artifact@v5
        with:
          name: trivy-report-xml
          path: trivy-report.xml
          retention-days: 30

      - name: Generate Trivy table report
        uses: aquasecurity/trivy-action@0.33.1
        with:
          exit-code: 0
          format: table
          hide-progress: true
          # image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          input: /tmp/output.tar.gz
          list-all-pkgs: true
          output: trivy-report.txt
          scanners: vuln,secret,config,license
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          skip-setup-trivy: true
          vuln-type: os,library

      - name: Publish Trivy Output to Summary
        run: |
          if [[ -s trivy-report.txt ]]
          then
            {
              echo "### Security Output"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```terraform'
              cat trivy-report.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          else
            echo "No security issues found using Trivy :)" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Generate Trivy sarif report
        uses: aquasecurity/trivy-action@0.33.1
        with:
          exit-code: 0
          format: sarif
          hide-progress: true
          list-all-pkgs: true
          output: trivy-report.sarif
          scanners: vuln,secret,config,license
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          skip-setup-trivy: true
          vuln-type: os,library

      - name: Upload Trivy sarif report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-reeport.sarif

      - name: Scan image with Trivy
        id: trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          exit-code: 1
          format: table
          hide-progress: true
          # image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          input: /tmp/output.tar.gz
          ignore-unfixed: true
          list-all-pkgs: true
          scanners: vuln,secret,config,license
          severity: CRITICAL
          skip-setup-trivy: true
          vuln-type: os,library

      # - name: Scan image with Anchore
      #   id: scan
      #   uses: anchore/scan-action@v7
      #   with:
      #     fail-build: true
      #     image: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
      #     output-format: table
      #     severity-cutoff: critical

      # # - name: Inspect action SARIF report
      # #   run: cat ${{ steps.scan.outputs.sarif }}

      # - name: Build and push image
      #   id: push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     labels: ${{ steps.meta.outputs.labels }}
      #     provenance: mode=max
      #     push: true
      #     sbom: true
      #     tags: ${{ steps.meta.outputs.tags }}

      # - name: Generate SBOM
      #   id: sbom
      #   uses: anchore/sbom-action@v0
      #   with:
      #     artifact-name: sbom.spdx.json
      #     image: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
      #     dependency-snapshot: true

      # # - name: Generate artifact attestation
      # #   uses: actions/attest-build-provenance@v3
      # #   with:
      # #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      # #     subject-digest: ${{ steps.push.outputs.digest }}
      # #     push-to-registry: true
